DrKabum/soil-apt

src/config/open-ai.ts
- reduce max response word count to 100
=> reduce to 100 words

.github/workflows/deploy.yml
fix bun path in deployment pipeline
=> fix bun path

src/chat-gpt/prompt.ts, src/commands/usage.ts, src/data/prompt.ts, src/helpers/format-big-number.ts
=> Add command to measure API usage

src/chat-gpt/open-ai.ts, src/chat-gpt/prompt.ts
on a reply, the bot will now fetch all replies of replies in the chain to provide full context of a conversation.
resolves #26
=> Get all replies on prompt

src/chat-gpt/open-ai.ts
=> Soil a dit bug

package.json, src/chat-gpt/open-ai.ts, src/commands/mood.ts, src/data/database.ts, src/data/persona.ts, src/data/personas.yaml, src/data/potd.ts, src/helpers/is-today.ts, src/helpers/pick-new-potd.ts, src/index.ts
- add a list of persona that the bot will inarnate.
- every day at midnight, Paris time, the bot will pick one randomly
- add a `/persona` command to see what personality the bot has at the moment
- maybe for later: add a command to change the persona?
=> Persona-of-the-day

src/data/personas.yaml
add a number of personas from @Kreusfel
- closes #34 
- closes #40 
- closes #51 
- closes #53 
- closes #54
=> add new personas

.github/ISSUE_TEMPLATE/nouvelle-personnalité.md
Make it more clear that we need some examples of the output
=> refactor persona issue template

src/chat-gpt/prompt.ts, src/commands/choose-persona.ts, src/data/persona.ts, src/helpers/potd-helpers.ts, src/index.ts, src/types.ts
=> Add command to change the bot's persona

src/data/personas.yaml
=> Add conspirationniste persona

.github/workflows/deploy-bot.yml
`deploy-bot.yml` should only trigger when changes are made to bot files
=> fix path in deploy bot workflow

.github/workflows/deploy-api-and-bot.yml
sooooo... absolute path, no package.json script :(
=> change for absolute paths, no package.json script

.github/workflows/build-publish-docker.yml
=> fix publishing workflow

.github/workflows/build-publish-docker.yml
=> 3rd fix for publishing workflow

.github/workflows/build-publish-docker.yml
=> 4th attempt: fix publishing workflow

.github/workflows/build-publish-docker.yml
=> 5th attempt to fix publishing workflow

.github/workflows/build-publish-docker.yml
=> 6th freaking attempts to fix publishing

docker-compose.yaml
=> docker-compose update

bot/chat-gpt/prompt.ts
The bot was way too hot 🥵 Back to values between 0 - 1.
=> 🔥Fix temperature back to a normal level

bot/chat-gpt/open-ai.ts
This PR fixes #94 where when creating context, posts with attachments were assigned to `system` prompts.
Now, other users posts are created as `user` but adds it with context about who said it (in a different message to avoid SoilAPT to start quote with "This guy said")
=> Fix #94: assign attachements to `system` prompts
